---
# tasks file for git

- name: remove old git
  yum:
     name: git*
     state: absent

- name: add repo
  yum:
     name: https://centos7.iuscommunity.org/ius-release.rpm
     state: present

- name: install git
  yum:
     name: git2u-all
     state: present
